// <auto-generated />
using System;
using MemoLingo.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MemoLingo.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260821232334_RenameUsuarioIdiomaToProgressoIdioma")]
    partial class RenameUsuarioIdiomaToProgressoIdioma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("MemoLingo.Api.Entities.Idioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Idiomas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "en",
                            Nome = "Inglês"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "pt",
                            Nome = "Português"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "es",
                            Nome = "Espanhol"
                        },
                        new
                        {
                            Id = 4,
                            Codigo = "it",
                            Nome = "Italiano"
                        });
                });

            modelBuilder.Entity("MemoLingo.Api.Entities.ProgressoIdioma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdiomaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCursoAtivo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OfensivaAtualDias")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLicoesConcluidas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPalavrasAprendidas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpTotal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdiomaId");

                    b.HasIndex("UsuarioId", "IdiomaId")
                        .IsUnique();

                    b.ToTable("ProgressosIdioma");
                });

            modelBuilder.Entity("MemoLingo.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("IdiomaMaternoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdiomaMaternoId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MemoLingo.Api.Entities.ProgressoIdioma", b =>
                {
                    b.HasOne("MemoLingo.Api.Entities.Idioma", "Idioma")
                        .WithMany()
                        .HasForeignKey("IdiomaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MemoLingo.Api.Entities.Usuario", "Usuario")
                        .WithMany("ProgressosIdioma")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idioma");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MemoLingo.Api.Entities.Usuario", b =>
                {
                    b.HasOne("MemoLingo.Api.Entities.Idioma", "IdiomaMaterno")
                        .WithMany()
                        .HasForeignKey("IdiomaMaternoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdiomaMaterno");
                });

            modelBuilder.Entity("MemoLingo.Api.Entities.Usuario", b =>
                {
                    b.Navigation("ProgressosIdioma");
                });
#pragma warning restore 612, 618
        }
    }
}
